# Multiple Logistic Regression in Python  - College Admission

### Overview
Predict college admission using Multiple Logistic Regression
 
### Builds on
None

### Run time
approx. 10-20 minutes

### Notes



In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



## Step 1: College Admission Data

Let's look at the college admission data.  Here, we have some student test scores, GPA, and Rank, followed by whether the student was admitted or not.


|gre  |gpa  |rank |  admitted |
|-----------------------------|
|380  |3.61 | 3   |    no     |
|660  |3.67 | 1   |    yes    |
|800  |4.0  | 1   |    yes    |
|640  |3.19 | 4   |    yes    |
|520  |2.93 | 4   |    no     |
|760  |3.0  | 2   |    yes    |

In [3]:
admissions = pd.read_csv("/data/college-admissions/admission-data.csv")


## Step 3: Split Data into training and Test

We will split our data into training and test so we can see how it performs.

**=> TODO: Use training / test split of 70%/30% **

In [ ]:
from sklearn.model_selection import train_test_split
 
train_x, test_x, train_y, test_y = train_test_split(feature_vector, 
                                                    labels, test_size=???)
print("training set = " , len(train_x))
print("testing set = " , len(test_x))

In [6]:
from sklearn.model_selection import train_test_split
 # REMOVE

feature_vector = admissions.iloc[:,0:3]
labels = admissions.iloc[:,3]
train_x, test_x, train_y, test_y = train_test_split(feature_vector, 
                                                    labels, test_size=.3)
print("training set = " , len(train_x))
print("testing set = " , len(test_x))

training set =  70
testing set =  30



## Step 4: Run logistic regression



In [9]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

# Fit the model
lrModel = lr.fit(train_x, train_y)

print(lrModel.coef_)

[[ 0.48324488  0.00120315 -0.49915723]
 [-0.0093794   0.00139123 -0.45382615]
 [ 0.77702984 -0.00534947  0.54565565]
 [-0.92576839  0.00115703 -0.4891325 ]]


## Step 5: Inspect Learning


## Step 6: Evaluate Model

### 6.1 Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix

predictions = lrModel.predict(test_x)
confusion_matrix(test_y, predictions)

### 6.2 :  ROC Curve & AUC

In [ ]:
from sklearn.metrics import roc_curve, auc

fpr, tpr, thresholds = roc_curve(test_y, predictions)
roc_auc = auc(fpr, tpr)



In [ ]:
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b',
label='AUC = %0.2f'% roc_auc)
plt.legend(loc='lower right')
plt.plot([0,1],[0,1],'r--')
plt.xlim([-0.1,1.2])
plt.ylim([-0.1,1.2])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

## Step 7: Run on the test data

**=>TODO: transform the test data **

In [14]:
## what is the name of test dataframe?
predictions = lrModel.predict(test_x)
predictions


array([2, 3, 2, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3, 2, 2, 3, 2, 2,
       2, 2, 3, 2, 2, 2, 3])

## Step 8: Calcuate Accuracy on Test Data

**=>TODO: evaluate the predictions **

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y, predictions)

0.40000000000000002

## Step 9: Run some predictions on new data

Let's take some new data, and run predictions on that.

**=>TODO: transform the new data in order to get feature vectors **

In [ ]:
newdata = pd.DataFrame({'gre' : [600, 700, 800], 
                        'gpa' : [4.0, 3.5, 3.2],
                        'rank': [1,   2,   3]}
             )
print(newdata)
